<?php

/**



 * The footer cusotmizer settings template for the theme!
 * Do not edit this file.
 * Editing this file may cause bugs on site.



 */




?>
 
 
 
 
<?php if(!is_user_logged_in())



    {
    echo '<div class="social-link">
            <h3>Follow us</h3>
            <ul>
            <li><a target="_blank" href="https://www.naeyc.org/">Children Education</a></li>
            <li><a target="_blank" href="https://www.theidioms.com/">Idiom Meaning</a></li>
            <li><a target="_blank" href="https://shayari.net/">Shayari.net</a></li>
            </ul>
    </div>';
    }


?>